quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=admin

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ecommerce_db
quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.schema-management.strategy = update
quarkus.hibernate-orm.log.sql=true

quarkus.oidc.auth-server-url=http://localhost:8180/realms/e-commerce-realm
quarkus.oidc.client-id=quarkus-app
quarkus.oidc.application-type=service